name: Install node js and python
description: Setup Python and NodeJS
inputs:
  pythonVersion:
    description: Version of python
    required: false
    default: '3.x'
  nodejsVerison:
    description: Node Version
    required: false
    default: '18.x'

outputs:
  repoOwner:
    description: Reposotory owner
    value: ${{steps.Vars.outputs.RepositoryOwner}}
    
  branch:
    description: BRanch info
    value: ${{steps.Vars.outputs.Defaultbracnh}}

  CICDkey:
    description: CICDkey info
    value: ${{steps.Vars.outputs.CICDkey}}
runs:
  using: composite

  steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Setup NodeJS
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
    - name: 
      id: Vars
      shell: bash
      run: |
        echo "RepositoryOwner=${{github.repository_owner}}" >> $GITHUB_OUTPUT
        echo "Defaultbracnh=main" >> $GITHUB_OUTPUT
        echo "CICDkey=SSSAAAASSS" >> $GITHUB_OUTPUT


















        
