name: Build Angular App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-angular:
    runs-on: ubuntu-latest

    concurrency:
      group: ci-${{ github.workflow }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v4

      - name: Set up build env
        uses: sasikiran0601/Setup-Python-and-Node-Env@v1
        with:
           pythonVersion: 3.10
           nodejsVerison: 18

      
